import { relations } from 'drizzle-orm';
import {
  boolean,
  doublePrecision,
  integer,
  jsonb,
  pgTable,
  serial,
  text,
  timestamp,
} from 'drizzle-orm/pg-core';

// 1. Users table (Firebase Auth UID integration)
export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  uid: text('uid').notNull().unique(),
  email: text('email').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
});

// Production App Users table (Mobile Number is the unique user ID)
export const appUsers = pgTable('app_users', {
  id: text('id').primaryKey(),
  phone: text('phone').notNull().unique(),
  name: text('name').notNull(),
  role: text('role').notNull(), // 'super_admin' | 'accountant' | 'field_partner' | 'managing_partner'
  firmId: text('firm_id'),
  firmCode: text('firm_code'),
  partnerId: text('partner_id'),
  pinCode: text('pin_code').notNull().default('9999'),
  mustChangePin: boolean('must_change_pin').notNull().default(true),
  status: text('status').notNull().default('active'),
  lastLoginAt: timestamp('last_login_at'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

// Legacy / sample entries table (retained to prevent non-interactive drop prompt)
export const entries = pgTable('entries', {
  id: serial('id').primaryKey(),
  userId: integer('user_id'),
  content: text('content'),
  date: text('date'),
  createdAt: timestamp('created_at').defaultNow(),
});

// 2. Tenant Firms table
export const firms = pgTable('firms', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  code: text('code').notNull(),
  location: text('location').notNull(),
  state: text('state').notNull(),
  sectors: jsonb('sectors').$type<string[]>().notNull(),
  subscriptionPlan: text('subscription_plan').notNull().default('enterprise'),
  mrrAmount: doublePrecision('mrr_amount').notNull().default(0),
  status: text('status').notNull().default('active'),
  createdDate: text('created_date').notNull(),
  proprietorName: text('proprietor_name'),
  proprietorPhone: text('proprietor_phone'),
  managingPartnerName: text('managing_partner_name').notNull(),
  managingPartnerPhone: text('managing_partner_phone').notNull(),
  gstin: text('gstin'),
  panNumber: text('pan_number'),
  businessType: text('business_type'),
  tradeName: text('trade_name'),
  officeAddress: text('office_address'),
  contactEmail: text('contact_email'),
  reraNumber: text('rera_number'),
  accountantName: text('accountant_name').notNull(),
  accountantPhone: text('accountant_phone').notNull(),
  featureFlags: jsonb('feature_flags').notNull(),
  encryptionStatus: text('encryption_status'),
  credentials: jsonb('credentials'),
  createdAt: timestamp('created_at').defaultNow(),
});

// 3. Projects table
export const projects = pgTable('projects', {
  id: text('id').primaryKey(),
  firmId: text('firm_id').notNull(),
  name: text('name').notNull(),
  code: text('code').notNull(),
  sector: text('sector').notNull(),
  location: text('location').notNull(),
  mandalDistrict: text('mandal_district'),
  surveyNumbers: text('survey_numbers'),
  approvalAuthority: text('approval_authority'),
  lpOrReraNumber: text('lp_or_rera_number'),
  extentValue: doublePrecision('extent_value').notNull().default(0),
  extentUnit: text('extent_unit').notNull().default('Acres'),
  roadWidth: integer('road_width'),
  openSpacePercent: doublePrecision('open_space_percent'),
  floorRatePerSqYard: doublePrecision('floor_rate_per_sq_yard'),
  baseSqFtRate: doublePrecision('base_sq_ft_rate'),
  totalEstimatedOutlay: doublePrecision('total_estimated_outlay'),
  status: text('status').notNull().default('active_sales'),
  startDate: text('start_date').notNull(),
  targetCompletionDate: text('target_completion_date'),
  partners: jsonb('partners').notNull().default([]),
  plotsCount: integer('plots_count'),
  notes: text('notes'),
  floorsCount: integer('floors_count'),
  facingPremium: doublePrecision('facing_premium'),
  contractType: text('contract_type'),
  retentionPercent: doublePrecision('retention_percent'),
  countersCount: integer('counters_count'),
  dailySalesTarget: doublePrecision('daily_sales_target'),
  securityDeposit: doublePrecision('security_deposit'),
  flatsPerFloor: integer('flats_per_floor'),
  floorPlans: jsonb('floor_plans'),
  amenities: jsonb('amenities'),
  totalResidentialSft: doublePrecision('total_residential_sft'),
  totalAmenitiesSft: doublePrecision('total_amenities_sft'),
  totalBuiltUpAreaSft: doublePrecision('total_built_up_area_sft'),
  plotDistribution: jsonb('plot_distribution'),
  layoutAmenities: jsonb('layout_amenities'),
  planDocuments: jsonb('plan_documents'),
  createdAt: timestamp('created_at').defaultNow(),
});

// 4. Plots table
export const plots = pgTable('plots', {
  id: serial('id').primaryKey(),
  firmId: text('firm_id'),
  projectId: text('project_id'),
  plotNumber: text('plot_number').notNull(),
  areaSqYards: doublePrecision('area_sq_yards').notNull(),
  facing: text('facing').notNull(),
  ratePerSqYard: doublePrecision('rate_per_sq_yard').notNull(),
  status: text('status').notNull().default('available'),
  buyerName: text('buyer_name'),
  buyerPhone: text('buyer_phone'),
  buyerAadhaar: text('buyer_aadhaar'),
  advanceReceived: doublePrecision('advance_received'),
  paymentMode: text('payment_mode'),
  paymentRefNumber: text('payment_ref_number'),
  bookedAt: text('booked_at'),
  paymentMilestone: text('payment_milestone'),
  notes: text('notes'),
  officialDocValue: doublePrecision('official_doc_value'),
  discountApprovedBy: text('discount_approved_by'),
  blockName: text('block_name'),
  dimensions: text('dimensions'),
  roadWidthFt: integer('road_width_ft'),
  marketingRequest: jsonb('marketing_request'),
  blockedByAgent: text('blocked_by_agent'),
  blockedForBuyer: text('blocked_for_buyer'),
  blockedAt: text('blocked_at'),
  blockedRate: doublePrecision('blocked_rate'),
  createdAt: timestamp('created_at').defaultNow(),
});

// 5. Apartment Units table
export const apartmentUnits = pgTable('apartment_units', {
  id: text('id').primaryKey(),
  firmId: text('firm_id'),
  projectId: text('project_id'),
  unitNumber: text('unit_number').notNull(),
  floor: integer('floor').notNull(),
  flatType: text('flat_type').notNull(),
  sftArea: doublePrecision('sft_area').notNull(),
  facing: text('facing').notNull(),
  baseRate: doublePrecision('base_rate').notNull(),
  facingPremium: doublePrecision('facing_premium').notNull().default(0),
  floorRise: doublePrecision('floor_rise').notNull().default(0),
  parkingFee: doublePrecision('parking_fee').notNull().default(0),
  amenitiesFee: doublePrecision('amenities_fee').notNull().default(0),
  status: text('status').notNull().default('available'),
  buyerName: text('buyer_name'),
  buyerPhone: text('buyer_phone'),
  advanceReceived: doublePrecision('advance_received').default(0),
  currentMilestone: text('current_milestone'),
  milestoneStage: text('milestone_stage'),
  officialDocValue: doublePrecision('official_doc_value'),
  discountApprovedBy: text('discount_approved_by'),
  createdAt: timestamp('created_at').defaultNow(),
});

// 6. Firm Accounts table
export const firmAccounts = pgTable('firm_accounts', {
  id: text('id').primaryKey(),
  firmId: text('firm_id').notNull(),
  accountName: text('account_name').notNull(),
  bankName: text('bank_name').notNull(),
  accountType: text('account_type').notNull(),
  accountNumber: text('account_number').notNull(),
  ifscCode: text('ifsc_code').notNull(),
  branchName: text('branch_name').notNull(),
  city: text('city').notNull(),
  currentBalance: doublePrecision('current_balance').notNull().default(0),
  openingBalance: doublePrecision('opening_balance').notNull().default(0),
  upiId: text('upi_id'),
  linkedProjectId: text('linked_project_id'),
  isPrimary: boolean('is_primary').notNull().default(false),
  status: text('status').notNull().default('active'),
  authorizedSignatories: jsonb('authorized_signatories').notNull().default([]),
  createdDate: text('created_date').notNull(),
  notes: text('notes'),
  recentTransactions: jsonb('recent_transactions').default([]),
  createdAt: timestamp('created_at').defaultNow(),
});

// 7. Firm Account Transactions table
export const firmAccountTransactions = pgTable('firm_account_transactions', {
  id: text('id').primaryKey(),
  accountId: text('account_id').notNull(),
  firmId: text('firm_id'),
  projectId: text('project_id'),
  date: text('date').notNull(),
  type: text('type').notNull(),
  amount: doublePrecision('amount').notNull(),
  description: text('description').notNull(),
  referenceNo: text('reference_no'),
  category: text('category').notNull(),
  partnerName: text('partner_name'),
  projectName: text('project_name'),
  balanceAfter: doublePrecision('balance_after').notNull(),
  enrolledBy: text('enrolled_by'),
  approvedBy: text('approved_by'),
  status: text('status').default('approved'),
  paymentMode: text('payment_mode'),
  notes: text('notes'),
  createdAt: timestamp('created_at').defaultNow(),
});

// 8. Project Expenses table
export const projectExpenses = pgTable('project_expenses', {
  id: text('id').primaryKey(),
  firmId: text('firm_id'),
  projectId: text('project_id'),
  category: text('category').notNull(),
  estimatedBudget: doublePrecision('estimated_budget').notNull().default(0),
  actualSpent: doublePrecision('actual_spent').notNull().default(0),
  vendorNotes: text('vendor_notes').notNull().default(''),
  officialTaxInvoicedAmount: doublePrecision('official_tax_invoiced_amount'),
  isOfficialTaxEligible: boolean('is_official_tax_eligible').default(false),
  createdAt: timestamp('created_at').defaultNow(),
});

// 9. Syndicate Partners table
export const syndicatePartners = pgTable('syndicate_partners', {
  id: text('id').primaryKey(),
  firmId: text('firm_id'),
  name: text('name').notNull(),
  phone: text('phone').notNull(),
  roleDescription: text('role_description').notNull(),
  avatarColor: text('avatar_color').notNull().default('bg-amber-500'),
  initialCapital: doublePrecision('initial_capital').notNull().default(0),
  actualInvested: doublePrecision('actual_invested').default(0),
  fixedEquityPercent: doublePrecision('fixed_equity_percent').notNull().default(0),
  drawings: doublePrecision('drawings').notNull().default(0),
  shareOfFieldExpenses: doublePrecision('share_of_field_expenses').notNull().default(0),
  stockDrawsValuation: doublePrecision('stock_draws_valuation').default(0),
  officialDeclaredCapital: doublePrecision('official_declared_capital'),
  userRole: text('user_role'),
  userStatus: text('user_status').default('active'),
  pinCode: text('pin_code'),
  dailySpendingLimit: doublePrecision('daily_spending_limit'),
  addedDate: text('added_date'),
  addedBy: text('added_by'),
  createdAt: timestamp('created_at').defaultNow(),
});

// 10. Individual Investments table
export const individualInvestments = pgTable('individual_investments', {
  id: text('id').primaryKey(),
  firmId: text('firm_id').notNull(),
  projectId: text('project_id').notNull(),
  partnerId: text('partner_id').notNull(),
  partnerName: text('partner_name').notNull(),
  amount: doublePrecision('amount').notNull(),
  accountId: text('account_id').notNull(),
  accountName: text('account_name').notNull(),
  accountType: text('account_type').notNull(),
  date: text('date').notNull(),
  purpose: text('purpose').notNull(),
  paymentMode: text('payment_mode').notNull(),
  referenceNo: text('reference_no').notNull(),
  notes: text('notes').notNull(),
  status: text('status').notNull().default('approved'),
  enrolledBy: text('enrolled_by').notNull(),
  approvedBy: text('approved_by'),
  approvedAt: text('approved_at'),
  coSignatory: text('co_signatory'),
  witnessName: text('witness_name'),
  cashVaultLocation: text('cash_vault_location'),
  rejectionReason: text('rejection_reason'),
  createdAt: timestamp('created_at').defaultNow(),
});

// 11. Field Expense Logs table
export const fieldExpenseLogs = pgTable('field_expense_logs', {
  id: text('id').primaryKey(),
  firmId: text('firm_id'),
  projectId: text('project_id'),
  partnerId: text('partner_id').notNull(),
  partnerName: text('partner_name').notNull(),
  amount: doublePrecision('amount').notNull(),
  category: text('category').notNull(),
  date: text('date').notNull(),
  note: text('note').notNull(),
  voiceNoteUrl: text('voice_note_url'),
  hasVoiceNote: boolean('has_voice_note').default(false),
  receiptImage: text('receipt_image'),
  status: text('status').notNull().default('pending'),
  reconciledDate: text('reconciled_date'),
  reconciledBy: text('reconciled_by'),
  requiresManagingPartnerSignoff: boolean('requires_managing_partner_signoff').default(false),
  approvedByPartners: jsonb('approved_by_partners').default([]),
  approvalSignatures: jsonb('approval_signatures').default([]),
  deviceId: text('device_id'),
  isOfficialTaxEligible: boolean('is_official_tax_eligible').default(false),
  taxInvoiceEligible: boolean('tax_invoice_eligible').default(false),
  isTaxOfficial: boolean('is_tax_official').default(false),
  taxInvoiceNo: text('tax_invoice_no'),
  vendorName: text('vendor_name'),
  paymentMode: text('payment_mode'),
  enrolledBy: text('enrolled_by'),
  createdAt: timestamp('created_at').defaultNow(),
});

// 12. Audit Logs table
export const auditLogs = pgTable('audit_logs', {
  id: text('id').primaryKey(),
  firmId: text('firm_id'),
  timestamp: text('timestamp').notNull(),
  partnerName: text('partner_name'),
  actorName: text('actor_name'),
  actorRole: text('actor_role'),
  action: text('action').notNull(),
  deviceId: text('device_id').notNull(),
  notes: text('notes').notNull(),
  impactAmount: doublePrecision('impact_amount'),
  ledgerType: text('ledger_type').notNull().default('Internal Syndicate'),
  verified: boolean('verified').notNull().default(false),
  createdAt: timestamp('created_at').defaultNow(),
});

// 13. System Meta & State table
export const systemMeta = pgTable('system_meta', {
  key: text('key').primaryKey(),
  value: jsonb('value').notNull(),
  updatedAt: timestamp('updated_at').defaultNow(),
});
